services:
  # --- FREE API (Flask) ---
  - type: web
    runtime: python
    name: pedestrian-api
    rootDir: api
    plan: free                  # <-- use the Free instance
    autoDeployTrigger: commit
    buildCommand: |
      apt-get update && apt-get install -y git-lfs || true
      git lfs install || true
      git lfs pull || true
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app -b 0.0.0.0:$PORT --timeout 180
    # ⚠️ No 'disk' section on Free; use /tmp for temp files
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DATA_DIR
        value: /tmp             # <-- write GPKGs to /tmp on Free
      - key: CORS_ORIGINS
        value: https://pedestrian-frontend.onrender.com,http://localhost:3000

  # --- FREE Static frontend ---
  - type: web
    runtime: static
    name: pedestrian-frontend
    rootDir: frontend
    buildCommand: ""
    staticPublishPath: .
